name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install Dependencies
        run: npm ci

      - name: access to secrets
        run: |
          echo "VITE_KAKAO_JAVASCRIPT_KEY=$VITE_KAKAO_JAVASCRIPT_KEY" >> .env
          echo "VITE_KAKAO_REST_API_KEY=$VITE_KAKAO_REST_API_KEY" >> .env
          echo "VITE_TRAVEL_API_KEY=$VITE_TRAVEL_API_KEY" >> .env
        env:
          VITE_KAKAO_JAVASCRIPT_KEY: ${{ secrets.VITE_KAKAO_JAVASCRIPT_KEY }}
          VITE_KAKAO_REST_API_KEY: ${{ secrets.VITE_KAKAO_REST_API_KEY }}
          VITE_TRAVEL_API_KEY: ${{ secrets.VITE_TRAVEL_API_KEY }}

      - name: Build
        run: npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 dist s3://wanderhub
